<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ClinicVets</AssemblyName>
    <RootNamespace>ClinicVets.Desktop</RootNamespace>
    <ApplicationTitle>ClinicVets</ApplicationTitle>
    <ApplicationIcon>..\..\assets\icons\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\icons\app.ico">
      <LogicalName>ClinicVets.app.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClinicVets.Application\ClinicVets.Application.csproj" />
    <ProjectReference Include="..\ClinicVets.Infrastructure\ClinicVets.Infrastructure.csproj" />
  </ItemGroup>

</Project>
