<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>ClinicVets</AssemblyName>
    <UseAppHost>true</UseAppHost>
    <ApplicationIcon>Assets\ClinicVets.ico</ApplicationIcon>
    <ApplicationManifest>Assets\app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.3" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="..\..\Tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\ClinicVets.ico" />
    <Content Include="Assets\ClinicVetsLogo.png" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\ClinicVets.ico" />
  </ItemGroup>
</Project>
